# Generated by Django 4.2 on 2024-12-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectMarks',
        ),
    ]
